server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

aws:
  region: "eu-north-1"
  s3:
    mock: true
    buckets:
      customer: "fs-msbeigi-customer-test"

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: msbeigi
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 50MB
  codec:
    max-in-memory-size: 10MB